
-- 1. 

SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS "주소지"
FROM TB_STUDENT
ORDER BY "학생 이름" ASC;

-- 2. 
SELECT STUDENT_NAME, STUDENT_SSN 
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY TO_NUMBER(SUBSTR(STUDENT_SSN, 1,6)) DESC;

-- 3. 
SELECT STUDENT_NAME "학생이름",
       STUDENT_NO "학번",
       STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE STUDENT_NO LIKE '9%' AND ( STUDENT_ADDRESS LIKE '%강원도%' OR  STUDENT_ADDRESS LIKE '%경기도%')
ORDER BY "학생이름";

-- 4. 

SELECT PROFESSOR_NAME, PROFESSOR_SSN 
FROM TB_PROFESSOR P
JOIN TB_DEPARTMENT D ON (P.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE D.DEPARTMENT_NAME = '법학과'
ORDER BY TO_NUMBER(SUBSTR(PROFESSOR_SSN, 1, 2));

-- 서브 쿼리 활용
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = (
    SELECT DEPARTMENT_NO FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME = '법학과'
    )
ORDER BY 2;

-- 5. 
SELECT STUDENT_NO, POINT
FROM TB_GRADE
WHERE CLASS_NO = 'C3118100' AND TERM_NO = '200402'
ORDER BY POINT DESC, STUDENT_NO ASC;

-- 6. 

SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
ORDER BY 2 ASC; 

-- 7
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS C
JOIN TB_DEPARTMENT D ON (C.DEPARTMENT_NO = D.DEPARTMENT_NO);

-- 8 
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS C
JOIN TB_CLASS_PROFESSOR CP ON (C.CLASS_NO = CP.CLASS_NO)
JOIN TB_PROFESSOR P ON (P.PROFESSOR_NO = CP.PROFESSOR_NO);


-- 9
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS C
JOIN TB_CLASS_PROFESSOR CP ON (C.CLASS_NO = CP.CLASS_NO)
JOIN TB_PROFESSOR P ON (P.PROFESSOR_NO = CP.PROFESSOR_NO)
WHERE C.DEPARTMENT_NO IN (SELECT DEPARTMENT_NO
                        FROM TB_DEPARTMENT
                        WHERE CATEGORY = '인문사회');
                        
-- 10 
SELECT "학번", "학생 이름", ROUND(AVG(POINT),1) 
FROM (SELECT S.STUDENT_NO "학번",
    S.STUDENT_NAME "학생 이름",
    POINT
    FROM TB_STUDENT S
    JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO) 
    WHERE S.DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME = '음악학과'))
GROUP BY "학번", "학생 이름"
ORDER BY "학번";

SELECT STUDENT_NO "학번",
        STUDENT_NAME "학생이름",
        ROUND(AVG(POINT),1 ) "전체 평점"
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO, STUDENT_NAME;

-- 11.     
SELECT DEPARTMENT_NAME "학과이름",
       STUDENT_NAME "학생이름",
       PROFESSOR_NAME "지도교수이름"
FROM TB_DEPARTMENT D
JOIN TB_STUDENT S ON (D.DEPARTMENT_NO = S.DEPARTMENT_NO)
JOIN TB_PROFESSOR P ON (S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
WHERE S.STUDENT_NO = 'A313047';
       
-- 12. 
SELECT S.STUDENT_NAME, G.TERM_NO
FROM TB_STUDENT S
JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
WHERE G.TERM_NO LIKE '2007%' AND
     G.CLASS_NO = (SELECT CLASS_NO FROM TB_CLASS WHERE CLASS_NAME = '인간관계론');

SELECT STUDENT_NAME, TERM_NO TERM_NAME
FROM TB_STUDENT 
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_CLASS USING(CLASS_NO)
WHERE CLASS_NAME = '인간관계론'
    AND TERM_NO LIKE '2007%';

-- 13. 
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS C
JOIN TB_DEPARTMENT D ON (C.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE D.CATEGORY = '예체능' AND 
      C.CLASS_NO NOT IN (SELECT CLASS_NO FROM TB_CLASS_PROFESSOR);

SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
LEFT JOIN TB_CLASS_PROFESSOR USING(CLASS_NO) -- 일치하는 행이 0개, 1~N개
WHERE CATEGORY = '예체능' AND PROFESSOR_NO IS NULL;

      
-- 14. 
SELECT STUDENT_NAME "학생이름" , NVL(PROFESSOR_NAME, '지도교수 미지정') "지도교수"
FROM TB_STUDENT S 
LEFT JOIN TB_PROFESSOR P ON (S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE S.DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME = '서반아어학과');

SELECT STUDENT_NAME "학생이름" , NVL(PROFESSOR_NAME, '지도교수 미지정') "지도교수"
FROM TB_STUDENT T1
LEFT JOIN TB_PROFESSOR T2 ON COACH_PROFESSOR_NO = PROFESSOR_NO
JOIN TB_DEPARTMENT T3 ON T1.DEPARTMENT_NO = T3.DEPARTMENT_NO
WHERE DEPARTMENT_NAME = '서반아어학과';


-- 15.
SELECT S.STUDENT_NO "학번",  S.STUDENT_NAME "이름" , D.DEPARTMENT_NAME "학과 이름" , ROUND(AVG(POINT),3) "평점"
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
WHERE S.ABSENCE_YN = 'N'
GROUP BY S.STUDENT_NO, S.STUDENT_NAME, D.DEPARTMENT_NAME
HAVING AVG(POINT) >= 4.0
ORDER BY 1;

SELECT 
     STUDENT_NO,
     STUDENT_NAME,
     DEPARTMENT_NAME,
     AVG(POINT)
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING AVG(POINT) >= 4.0;

        

--16. 

SELECT C.CLASS_NO, C.CLASS_NAME, TRUNC(AVG(G.POINT),8)
FROM TB_CLASS C
JOIN TB_GRADE G ON (C.CLASS_NO = G.CLASS_NO)
WHERE C.DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME = '환경조경학과') AND 
    C.CLASS_TYPE LIKE '%전공%'
GROUP BY C.CLASS_NO, C.CLASS_NAME
ORDER BY 1;

SELECT 
    CLASS_NO,
    CLASS_NAME,
    AVG(POINT)
FROM TB_CLASS
JOIN TB_GRADE USING(CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과' AND CLASS_TYPE LIKE '%전공%'
GROUP BY CLASS_NO, CLASS_NAME;

-- 17. 
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON(S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE S.DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_DEPARTMENT 
                            WHERE DEPARTMENT_NO = (
                                SELECT DEPARTMENT_NO FROM TB_STUDENT
                                WHERE STUDENT_NAME = '최경희'
                                )
                            );
                            
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON(S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE D.DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_STUDENT WHERE STUDENT_NAME = '최경희');

SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_STUDENT WHERE STUDENT_NAME = '최경희');
-- 약간 위험한 코드('최경희' 라는 이름의 동명이인이 있을때 조건이 맞지 않을 수 있다.)

-- 18. 
SELECT STUDENT_NO, 
       STUDENT_NAME,
       AVG(POINT)
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
GROUP BY STUDENT_NO, STUDENT_NAME
HAVING AVG(POINT) = (SELECT MAX(AVG(POINT)) FROM TB_STUDENT 
                        JOIN TB_GRADE USING(STUDENT_NO)
                        JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
                        WHERE DEPARTMENT_NAME = '국어국문학과'
                        GROUP BY STUDENT_NO, STUDENT_NAME);

SELECT *
FROM (SELECT STUDENT_NO, 
       STUDENT_NAME,
       AVG(POINT)
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
GROUP BY STUDENT_NO, STUDENT_NAME
ORDER BY 3 DESC)
WHERE ROWNUM = 1;


-- 19. 
SELECT DEPARTMENT_NAME "계열 학과명", ROUND(AVG(POINT), 1) "전공평점"
FROM TB_DEPARTMENT
JOIN TB_CLASS USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(CLASS_NO)
WHERE CATEGORY = (SELECT CATEGORY FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME = '환경조경학과')
      AND CLASS_TYPE LIKE '%전공%'
GROUP BY DEPARTMENT_NAME;



