
-- 1
SELECT
    STUDENT_NO 학번,
    STUDENT_NAME 이름,
    TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD' ) 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY 입학년도;

-- 2. 
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) !=3;

-- 3. 
SELECT PROFESSOR_NAME 교수이름, 
       EXTRACT(YEAR FROM SYSDATE) - TO_NUMBER('19' || SUBSTR(PROFESSOR_SSN, 1, 2)) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) = 1
ORDER BY 나이;

-- 4. 
SELECT SUBSTR(PROFESSOR_NAME,2) 이름
FROM TB_PROFESSOR;

-- 5. 
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,2),'RRRR')) >= 20;


-- 6. 
SELECT CASE TO_CHAR(TO_DATE('20/12/25', 'YY/MM/DD'), 'D')
        WHEN '1' THEN '일요일'
        WHEN '2' THEN '월요일'
        WHEN '3' THEN '화요일'
        WHEN '4' THEN '수요일'
        WHEN '5' THEN '목요일'
        WHEN '6' THEN '금요일'
        WHEN '7' THEN '토요일'
        END 요일
FROM DUAL; 

-- 7. 
SELECT TO_DATE('99/10/11', 'YY/MM/DD')
FROM DUAL;

SELECT TO_DATE('49/10/11', 'YY/MM/DD')
FROM DUAL;

SELECT TO_DATE('99/10/11', 'RR/MM/DD')
FROM DUAL;

SELECT TO_DATE('49/10/11', 'RR/MM/DD')
FROM DUAL;

-- 8. 
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO, 1,1) != 'A'; 

-- 9 
SELECT ROUND(AVG(POINT), 1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- 10. 
SELECT DEPARTMENT_NO "학과번호" , COUNT(*) "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- 11. 
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

-- 12. 
SELECT SUBSTR(TERM_NO, 1, 4) AS "년도", 
     ROUND(AVG(POINT),1) AS "년도 별 평점" 
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4);

-- 13. 
SELECT DEPARTMENT_NO AS "학과코드명", COUNT(CASE ABSENCE_YN WHEN 'Y' THEN 1234 ELSE NULL END) AS "휴학생 수" 
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- 14. 
SELECT STUDENT_NAME AS "동일이름", COUNT(*) AS "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) !=1
ORDER BY STUDENT_NAME;


-- 15. 

-- <강사님 풀이> 
-- UNION ALL 사용 
SELECT SUBSTR(TERM_NO,1,4) 년도,
       SUBSTR(TERM_NO,5,2) 학기,
       ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4), SUBSTR(TERM_NO,5,2)
UNION ALL 
SELECT SUBSTR(TERM_NO,1,4) 년도,
       NULL,
       ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4)
UNION ALL
SELECT NULL,
       NULL,
       ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
ORDER BY 년도, 2;

-- ROLL UP 사용 
SELECT SUBSTR(TERM_NO,1,4) 년도,
       SUBSTR(TERM_NO,5,2) 학기,
       ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4), SUBSTR(TERM_NO,5,2))
ORDER BY 1;

-- <내가 푼 풀이> 
-- GROPPING, ROLL UP 사용
SELECT 
       CASE 
            WHEN GROUPING(SUBSTR(TERM_NO, 1,4)) = 1 THEN '총합'
            ELSE SUBSTR(TERM_NO, 1,4) END AS "년도",
       CASE 
            WHEN GROUPING(SUBSTR(TERM_NO, 5)) = 1 THEN '소계'
            ELSE SUBSTR(TERM_NO, 5) END AS "학기",
       ROUND(AVG(POINT),1)
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO, 1,4), SUBSTR(TERM_NO, 5));
