--  부서별 가장 낮은 급여를 가진 사람
SELECT DEPT_CODE, MIN(SALARY)
FROM EMPLOYEE
GROUP BY DEPT_CODE
ORDER BY 2;


-- 부서별 가장 낮은 급여를 가진 사람
-- 중첩쿼리와 IN 사용
SELECT EMP_NAME, SALARY
FROM EMPLOYEE
WHERE (DEPT_CODE, SALARY) IN (SELECT DEPT_CODE,MIN(SALARY) FROM EMPLOYEE GROUP BY DEPT_CODE)
ORDER BY SALARY;
